### ISSUE TITLE
EXAMPLES.md semi column is missing

### ISSUE THREAD

**Issue by kikiazerty** [sabas/edifact#10]
Hi

in EXAMPLES.md on section EDI data element reading

 $record = array(
            'interchangeSender' => $reader->readEdiDataValue('UNB',2),
            'arrivalDateTimeEstimated' => $reader->$EdiReader->readEdiSegmentDTM('132'),
            'messageReferenceNumber' => $reader->readEdiDataValue('UNH',1),
            'TareWeight' => $reader->readEdiDataValue(['MEA',['2'=>'T']],3,0) 
                                . ' ' 
                                . $reader->readEdiDataValue(['MEA',['2'=>'T']],3,1),
            'GrossWeight' => $reader->readEdiDataValue(['MEA',['2'=>'G']],3,0) 
                                . ' ' 
                                . $reader->readEdiDataValue(['MEA',['2'=>'G']],3,1),
    );

the last semi column is missing

regards i thanks for your project

christophe

**Comment by sabas** [comment]
Thanks!
