### ISSUE TITLE
Array format for Encoder

### ISSUE THREAD

**Issue by salvisb** [sabas/edifact#12]
Greetings!
How array must be formatted for passing to Encoder?

Thanks!

**Comment by sabas** [comment]
Hi, 
array containing an array for each segment. Each segment should have for simple elements a string and for composite elements an array. (The function simply implodes with correct separators and does escaping). 
Let me know if you get a valid message!  :-)

**Comment by salvisb** [comment]
So far it's ok! Thanks!:)

**Comment by uldisn** [comment]
Salvi, ar kādu projektu ņemies?

**Comment by salvisb** [comment]
Plānojas iepirkumu dokumentu apmaiņas ieviešana ERP sistēmā. Pagaidām tāda taustīšanās, nav pieredze ar EDI.:)

**Comment by uldisn** [comment]
Te manējais darbs, kur izmantoju EDI: http://www.weberp.lv/lv/sistemas/konteineri

**Comment by salvisb** [comment]
Uldi, varbūt vari pakonsultēt šādā jautājumā. Teiksim nosūtot purchase order un saņemot atbildi man ir jāzina uz kuru purchase order šī atbilde attiecās. Kā panākt, lai manis sūtītais id figurētu atbildes ziņojumā? Kur tas ir liekams EDI dokumenta struktūrā?

**Comment by sabas** [comment]
English would be better for me ;)

**Comment by salvisb** [comment]
@sabas , sorry this particular question was intended directly for @uldisn. 

I am interested in EDI document exchange as a whole. I am asking what is correct way to reference, for example, particular purchase order in response message.
If I would place in LIN segment material unique number - ID, can I get exact ID in response message?

**Comment by uldisn** [comment]
Sorry Stefano! We talk about local project problems!
Salvi, call me +371 26312211

**Comment by sabas** [comment]
No problem for me, it only that when I'll close this issue the discussion will continue to be readable by others ;-)

**Comment by sabas** [comment]
I believe this issue can be closed :-)
