### ISSUE TITLE
EDI Translation for error reporting

### ISSUE THREAD

**Issue by salvisb** [sabas/edifact#13]
Greetings!

Does EDI Analyser somehow can be used to identify errors (for example when some of the elements are too long, missing mandatory segment etc.)? 
Or it renders only description about each segment and data element?

**Comment by sabas** [comment]
It only prints description. 
The only validation occurs in the reader at the moment.

@uldisn

**Comment by uldisn** [comment]
- Required segments for example for codeco you can get from https://github.com/sabas/edifact/blob/master/src/EDI/Mapping/D95B/messages/codeco.xml
 - segment rules described in https://github.com/sabas/edifact/blob/master/src/EDI/Mapping/D95B/messages/codeco.xml

You can add validation in Analyser.php
