### ISSUE TITLE
Adding package via composer returns: "Could not find package in any version"

### ISSUE THREAD

**Issue by Xiro** [sabas/edifact#16]
If I try to add the project via the composer by executing `composer require sabas/edifact` I get the following error:
```
[InvalidArgumentException]
Could not find package sabas/edifact at any version for your minimum-stability (stable). Check the package spelling or your minimum stability
```

Even if I add `--dev` the composer won't add the package. This error usually occurs if you don't tag your commits with a version name before pushing them. The only way to get the package at the moment is:

```
  "require": {
    "sabas/edifact": "*@dev"
  },
```

The tags don't need to be stable, but the composer needs tags in order to pull the package and won't look for the version you defined in `composer.json`

**Comment by sabas** [comment]
Could you suggest how to modify it? (as a pull request if you want).

**Comment by Xiro** [comment]
Sure, I added a tag in the last pull request, but I'm not sure if Git will add tags of a pull request as well, maybe you need to do this. You can find the description how to tag [here](https://git-scm.com/book/en/v2/Git-Basics-Tagging)
Usually you will do something like this:
```
git commit
git tag -a 0.0.2
git push --tags
```
Just add a tag after you commited all changes before the push. Tags that were created after pushing the commits will not be linked to those commits

**Comment by sabas** [comment]
I try to tag it now.

**Comment by Xiro** [comment]
Doesn't seem like the tag was merged. You could try to get all tags by running `git tag` but I doubt you will be able to pull it.
Oh and you will need some commit, too, so your tag can be attached to some changes. Some whitespace changes are enough.

**Comment by sabas** [comment]
Done, I hope :-)

**Comment by Xiro** [comment]
Perfect, it works :-) Thanks for the quick support!

**Comment by sabas** [comment]
Thanks to you for the PR and the suggestions :-)
I close the issue
