### ISSUE TITLE
Parser seems to be slow

### ISSUE THREAD

**Issue by eschmid72** [sabas/edifact#21]
I think your parser is slow.
It's maybe besser to use the `explode()` function than regexp's. Or are those regexp's necessary?

**Comment by sabas** [comment]
explode is faster than preg_split yes, but it would be useful only on splitting on simple separators. For edifact we need to take in account occurrences of different characters and split only if the character is not escaped (for example: split on ```+``` but not when there's ```?+```) and this is done using backreferences.

Another parsing solution would be using a tokenizer, but I didn't look into it yet. :-)
