### ISSUE TITLE
Errors after $parser->load($file);

### ISSUE THREAD

**Issue by jiff88** [sabas/edifact#22]
Please take this as a suggestion / question more than an issue.
I expect this usage is legit:

```php
// may be very heavy object
$parser = new \EDI\Parser();

// load file 1/150
$parser->load($file);
$parser->errors();

// load file 2/150
$parser->load($file);
$parser->errors();
```

But the errors get appended, load() doesn't clear the collection. I am not saying it should be exactly like this, but i think this way of usage is not so good:

```php
foreach ($files as $file) {
    // gets created every time
    $parser = new \EDI\Parser();			
    $parser->load($file);
    $parser->errors();			
}
```

Thank you for your thoughts..
Josef

**Comment by sabas** [comment]
What about initializing the errors array in the parse function? (after line 38 https://github.com/sabas/edifact/blob/master/src/EDI/Parser.php#L38)
So it should reset itself at each load().

(in a bulk process I use at work I actually build a new object for each message because it's an ajax call)

**Comment by jiff88** [comment]
Hmm.. don't like the idea that much, because:

```
$parser = new \EDI\Parser();

$parser->load($file);
$parser->parse();
$parser->errors();

$parser->load($anotherFile);
// errors are here, from the previous parsing, and are not related to $anotherFile
$parser->errors();
```

Personally, i think the better place is the load() and loadString() functions as they are the "entry calls".
Josef

**Comment by sabas** [comment]
But parse() can also be called directly (the constructor calls parse if the data is an array) while load and loadString call parse to do the actual processing. An hypothetical test case would fail if passed an array with errors two times imho...

I committed a fix, if you want to test from master (but I didn't tag it yet).

**Comment by jiff88** [comment]
Cool, looks fine by me, thank you

**Comment by sabas** [comment]
Ok, I tagged a new version for your convenience :-)
