### ISSUE TITLE
How to implement service_codes_v3.xml?

### ISSUE THREAD

**Issue by millemedia** [sabas/edifact#23]
For a project I need to implement the service_codes_v3.xml in Analyser.php, because the lack of these codes results in errors. Is there a way to implement this?

Best regards

Andreas

**Comment by sabas** [comment]
Could you explain better? Which is the error it's giving you?
Probably you could solve with an isset() somewhere...

**Comment by millemedia** [comment]
I need to convert an edi message of type IFSTA (Container track & trace) with the information stored in folder D95B. The first segment begins with "UNA:+,? 'UNB+UNOC:1+XXXX:ZZZ+YYYY:ZZZ+151115:1001+15018", where XXXX:ZZZ is the sender and YYYY:ZZZ is the reciever.
If I use the Analyzer.php to show the field descriptions the sequence UNOC:1 is identified as reciever and therefore the analysing fails. I checked the code of Analyser.php an the information in Folder D95B and find out that the information of UNOC is stored in the xml file service_codes_v3.xml. But I did not find any example or function, that will load this file in Analyser.php to identify the information.

**Comment by sabas** [comment]
For the Analyser.php @uldisn could help you I think.

In my opinion you could start by implementing your own interpreter (reader of the array coming from EDI\Parser) if you need to focus on IFTSTA, following the format you usually receive and using the xml if you need.
