### ISSUE TITLE
Analyser breaks on EDI file with no newlines

### ISSUE THREAD

**Issue by emilv** [sabas/edifact#26]
I have an EDI file without line breaks which breaks the Analyser on [line 178](https://github.com/sabas/edifact/blob/ba68f597d27c288743f8dc5e2b02b07ffd1e0910/src/EDI/Analyser.php#L178). Newlines are optional and [Wikipedia](https://en.wikipedia.org/wiki/EDIFACT#Example) even states that:

> Note: The line breaks after each segment in this example have been added for readability. There are typically no line breaks in EDI data.

This is not caught by the unit tests since `example.edi` does indeed contain line breaks.

I understand that the purpose is to show only the current segment in raw format before each explanation. Just putting line 178 inside an `if` statement would solve the problem but also remove that feature. I'm not really sure what the best course of action would be here. Perhaps making `loadEdiMessage` split on the segment separator instead of linebreaks? But that would also mean we have to actually parse parts of the message inside the Analyser.

Perhaps some refactoring is in order:

* Remove `Analyser::loadEdiMessage`
* Add functionality to read raw segment from `Parser`

This would also remove the need to load the file twice for analysis since the Parser already have it.

What do you think?

**Comment by sabas** [comment]
The line break can occur if the sender likes it :-) I receive messages also with 2 line breaks between each segment from a provider...

Btw if you want to revise Analyser.php you can, just try to give a similar functionality (or if you have a better alternative we can discuss it!)

My idea of achieving the same feature would be:
- load the parsed message
- load the xml corresponding to the message (simpledom or xpath)
- output the analysis

I did this with xpath 2 years ago but never actually used it.  Here's a fragment from the code but never tested against current release (I never run an human readable analysis :D )
```
	/* load XML information */
	public function xmlSeg($type)
	{
		if(!isset($this->xmlinstance)) $this->xmlinstance=simplexml_load_file("edilib/d95b_segments.xml");
		$result = $this->xmlinstance->xpath('segment[@id="'.$type.'"]')[0];
		return $result;
	}
	
	public function xmlCode($id)
	{
		if(!isset($this->xmltranslation)) $this->xmltranslation=simplexml_load_file("edilib/d95b_codes.xml");
		$result = $this->xmltranslation->xpath('data_element[@id="'.$id.'"]');
		return $result;
	}
```


/cc @uldisn

**Comment by uldisn** [comment]
Hi!
I sugest other solution, for getting sanitised EDI row. For splitting to array, use https://github.com/sabas/edifact/blob/master/src/EDI/Parser.php#L61
and for sanitasing https://github.com/sabas/edifact/blob/master/src/EDI/Parser.php#L42 and https://github.com/sabas/edifact/blob/master/src/EDI/Parser.php#L46

**Comment by emilv** [comment]
See #27 for the refactoring I had in mind. This does not fix everything bothersome with the interface (for example, one could argue that we should just pass a Parser object directly into the Analyser, or let the Analyser create its own Parser object, or...), but is similar to the previous interface. All a user really have to care about is the dropped support for loading a file into the Analyser. It now expects a parsed array only.

**Comment by emilv** [comment]
@uldisn You mean that we should open up the interface from Parser and use those functions directly inside Analyser? I am not a fan of such tight coupling. The Analyser does not need to know how the Parser parsed the data.

**Comment by emilv** [comment]
:+1:
