### ISSUE TITLE
Display JSON Data attribute label

### ISSUE THREAD

**Issue by mtrayn01** [sabas/edifact#32]
Is there a way to display the data in JSON format, but include the attribute label?

Instead of just this:
[["UNB",["UNOA","2"],"OOCLIES","LBCTI",["160401","1523"],"13","","","","",""]

Something like this for example:
{"SyntaxIdentifier":"UNOA","SyntaxVersionNumber":2,"SenderIdentification":"OOCLIES","RecipientIdentification":"LBCTI","DateOfPreparation":"160401",

**Comment by sabas** [comment]
Modifying Analyser.php you can make an array and dump in to json
Example for the simple data elements
```
$readSegment[]=[$d_desc_attr['name'] => $detail];
```
For composite data elements I was wondering why it doesn't work..
Test case
```
EQD+CN+TSTU8127384+4300:102:5++2+5'
DTM+7:200506230616:203'
```
