### ISSUE TITLE
File parses in 0.0.6 but fails to parse with no error in dev-master

### ISSUE THREAD

**Issue by mtdavidson** [sabas/edifact#38]
Hi 

We've received an example EDI file from a supplier we are working with and I was just trying out the library to see if it would work. 

I've found that in 0.0.6 it seems to work fine

Doing

```
use EDI\Parser;
$fn="storage/sampleDESADV2.INT";
$p=new EDI\Parser($fn);
echo json_encode($p->get());
```

results in

`[["UNH","1",["DESADV","0","96A","UN"]],["BGM","351","FOM0000123","9"],["DTM",["11","20140313","102"]],["RFF",["ON","MULTI"]],["NAD","SU",["1556150UK","","31B"]],["NAD","BY",["8888888 01UK","","31B"]],["CPS","1"],["LIN","1"],["PIA","5",["9780071744225","EN"]],["QTY",["12","1"]],["RFF",["ON","0000000004000"]],["RFF",["LI","248127"]],["LIN","2"],["PIA","5",["9780091954925","EN"]],["QTY",["12","1"]],["RFF",["ON","0000000004003"]],["RFF",["LI","248230"]],["LIN","3"],["PIA","5",["9780099429760","EN"]],["QTY",["12","1"]],["RFF",["ON","0000000004007"]],["RFF",["LI","248408"]],["LIN","4"],["PIA","5",["9780099441441","EN"]],["QTY",["12","1"]],["RFF",["ON","0000000004007"]],["RFF",["LI","248409"]],["LIN","5"],["PIA","5",["9780099585336","EN"]],["QTY",["12","1"]],["RFF",["ON","0000000004006"]],["RFF",["LI","248349"]],["LIN","6"],["PIA","5",["9780099585336","EN"]],["QTY",["12","1"]],["RFF",["ON","0000000004009"]],["RFF",["LI","248512"]],["LIN","7"],["PIA","5",["9780141186917","EN"]],["QTY",["12","1"]],["RFF",["ON","0000000003990"]],["RFF",["LI","247741"]],["LIN","8"],["PIA","5",["9780143122791","EN"]],["QTY",["12","1"]],["RFF",["ON","0000000003992"]],["RFF",["LI","247874"]],["LIN","9"],["PIA","5",["9780749910549","EN"]],["QTY",["12","1"]],["RFF",["ON","0000000003987"]],["RFF",["LI","247485"]],["LIN","10"],["PIA","5",["9780749910549","EN"]],["QTY",["12","1"]],["RFF",["ON","0000000003988"]],["RFF",["LI","247628"]],["LIN","11"],["PIA","5",["9780749941659","EN"]],["QTY",["12","1"]],["RFF",["ON","0000000003991"]],["RFF",["LI","247751"]],["LIN","12"],["PIA","5",["9780753540329","EN"]],["QTY",["12","1"]],["RFF",["ON","0000000004005"]],["RFF",["LI","248306"]],["LIN","13"],["PIA","5",["9781408248737","EN"]],["QTY",["12","1"]],["RFF",["ON","0000000003985"]],["RFF",["LI","247354"]],["LIN","14"],["PIA","5",["9781591846284","EN"]],["QTY",["12","1"]],["RFF",["ON","0000000003998"]],["RFF",["LI","248030"]],["LIN","15"],["PIA","5",["9781742373386","EN"]],["QTY",["12","1"]],["RFF",["ON","0000000003999"]],["RFF",["LI","248060"]],["CNT",["2","15"]],["UNT","85","1"],["UNE","1","000000312"],["UNZ","1","000000312"]]`

however doing the same with the dev-master branch I just see

`[]`

I've checked the errors and that also shows

`[]`

I'd question the file but since it worked in the previous version I'm wondering if something that has changed and the file format is no longer parsing correctly?

The sample file I have is https://gist.github.com/mtdavidson/9223b0d083ee4c8e789c420a844a61f6

Any help would be appreciated I'm quite happy to pick through the library try figure out whats going on but I thought I'd better ask first incase someone more experienced with the EDI format might be able to shed some light. 

Thanks

Mark

**Comment by sabas** [comment]
Well, there's no segment terminator in that edi :-)
There should be a single quote ( ' ) at the end of each row. In fact it gives 85 segments adding it.
No error is given probably because the detection in splitSegment() function doesn't really work :/

**Comment by mtdavidson** [comment]
@sabas Thanks very much for your quick response.

Just wondering is it always a `'` as the segment terminator or does that sometimes vary like in this case could the supplier be treating the new line as the segment seperator?

**Comment by sabas** [comment]
It's in the edifact specification, so this should be the standard..
http://www.unece.org/fileadmin/DAM/trade/untdid/texts/d423.htm#p8.1

**Comment by mtdavidson** [comment]
Great thanks for the assistance will go back to the supplier and see what they have to say about it.
